[package]
name = 'getargs-os'
version = '0.1.0'
edition = '2021'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getargs = '~0.5.0'

[dev-dependencies]
argv = '~0.1.6'
